"""
Prototype: Threat Detection Service Skeleton
- FastAPI app with endpoints: /detect, /events, /mitigate, /generate_event
- SQLite backend for logs & events
- ThreatManager class that instantiates models in a loop
- Simple pretrained-like models (IsolationForest, RandomForest, LightGBM placeholder)
- Simulated DeepLog/LogBERT behavior (keyword/sequence checks)
- Background task that periodically pulls new data from DB and runs models
- LLM mitigation placeholder (Gemini Pro or OpenAI) — replace call_llm() with real API logic

Dependencies:
pip install fastapi uvicorn scikit-learn pandas numpy lightgbm aiofiles

Run:
uvicorn detector_prototype_fastapi:app --reload

This file is intentionally modular so you can expand models or swap in real pretrained checkpoints.
"""

import sqlite3
import threading
import time
import asyncio
import json
from typing import List, Dict, Any
from fastapi import FastAPI, BackgroundTasks, HTTPException
from pydantic import BaseModel
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from lightgbm import LGBMClassifier

DB_PATH = "detector_demo.db"
POLL_INTERVAL_SECONDS = 10  # how often ThreatManager pulls new data

# -------------------------
# Database helper (SQLite)
# -------------------------
def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    # raw_logs: incoming telemetry rows
    c.execute('''
        CREATE TABLE IF NOT EXISTS raw_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            host_id TEXT,
            src_ip TEXT,
            dst_ip TEXT,
            event_type TEXT,
            event_text TEXT,
            bytes_sent INTEGER,
            bytes_received INTEGER,
            processed INTEGER DEFAULT 0
        )
    ''')
    # events: alerts generated by models
    c.execute('''
        CREATE TABLE IF NOT EXISTS events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            name TEXT,
            severity TEXT,
            details TEXT,
            mitigated INTEGER DEFAULT 0
        )
    ''')
    conn.commit()
    conn.close()


def write_raw_log(row: Dict[str, Any]):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('''INSERT INTO raw_logs (timestamp, host_id, src_ip, dst_ip, event_type, event_text, bytes_sent, bytes_received)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?)''',
              (row.get('timestamp'), row.get('host_id'), row.get('src_ip'), row.get('dst_ip'),
               row.get('event_type'), row.get('event_text'), row.get('bytes_sent', 0), row.get('bytes_received', 0)))
    conn.commit()
    conn.close()


def fetch_unprocessed_logs(limit: int = 100) -> List[Dict[str, Any]]:
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('SELECT id, timestamp, host_id, src_ip, dst_ip, event_type, event_text, bytes_sent, bytes_received FROM raw_logs WHERE processed = 0 LIMIT ?', (limit,))
    rows = c.fetchall()
    conn.close()
    keys = ['id', 'timestamp', 'host_id', 'src_ip', 'dst_ip', 'event_type', 'event_text', 'bytes_sent', 'bytes_received']
    return [dict(zip(keys, r)) for r in rows]


def mark_logs_processed(ids: List[int]):
    if not ids:
        return
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(f'UPDATE raw_logs SET processed = 1 WHERE id IN ({",".join(["?"]*len(ids))})', ids)
    conn.commit()
    conn.close()


def write_event(name: str, severity: str, details: Dict[str, Any]):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('INSERT INTO events (timestamp, name, severity, details) VALUES (datetime("now"), ?, ?, ?)',
              (name, severity, json.dumps(details)))
    conn.commit()
    conn.close()


def list_events(limit: int = 100) -> List[Dict[str, Any]]:
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('SELECT id, timestamp, name, severity, details, mitigated FROM events ORDER BY id DESC LIMIT ?', (limit,))
    rows = c.fetchall()
    conn.close()
    keys = ['id', 'timestamp', 'name', 'severity', 'details', 'mitigated']
    return [dict(zip(keys, r)) for r in rows]


# -------------------------
# Models / Model wrappers
# -------------------------
class SimpleIsolationForestModel:
    def __init__(self, contamination=0.05):
        self.model = IsolationForest(n_estimators=100, contamination=contamination, random_state=42)
        # For demo: fit on trivial normal data
        X = np.array([[100, 200], [120, 220], [90, 180]])  # [bytes_sent, bytes_received]
        scaler = StandardScaler()
        self.scaler = scaler.fit(X)
        Xs = self.scaler.transform(X)
        self.model.fit(Xs)

    def predict(self, features: Dict[str, Any]):
        x = np.array([[features.get('bytes_sent', 0), features.get('bytes_received', 0)]])
        x_scaled = self.scaler.transform(x)
        pred = self.model.predict(x_scaled)  # 1 normal, -1 anomaly
        score = self.model.decision_function(x_scaled)[0]
        return {'anomaly': bool(pred[0] == -1), 'score': float(score)}


class SimpleRandomForestNetModel:
    """Supervised network model: train quickly on toy data"""
    def __init__(self):
        # toy training
        X = np.array([[200, 300, 1], [40000, 10, 0.2], [500, 600, 2]])
        y = np.array([0, 1, 0])
        self.model = RandomForestClassifier(n_estimators=10, random_state=42)
        self.model.fit(X, y)

    def predict(self, features: Dict[str, Any]):
        x = np.array([[features.get('bytes_sent', 0), features.get('bytes_received', 0), features.get('duration', 1)]])
        pred = self.model.predict(x)[0]
        prob = self.model.predict_proba(x).tolist()[0] if hasattr(self.model, 'predict_proba') else [0.0, 1.0]
        return {'attack': bool(pred == 1), 'prob': prob}


class EmberLikeMalwareModel:
    def __init__(self):
        # LightGBM toy classifier for binaries
        X = np.array([[120000, 30], [20000, 200], [5000000, 5]])
        y = np.array([0, 0, 1])
        self.model = LGBMClassifier()
        self.model.fit(X, y)

    def predict(self, features: Dict[str, Any]):
        x = np.array([[features.get('file_size', 0), features.get('num_imports', 0)]])
        pred = int(self.model.predict(x)[0])
        return {'malware': bool(pred == 1)}


# Simple rule-based simulators for DeepLog / LogBERT
class DeepLogLike:
    def predict(self, sequence: List[str]):
        # naive: if sequence contains forbidden pattern -> anomaly
        forbidden = ['rm -rf /', 'mimikatz', 'suspicious-lateral']
        for token in forbidden:
            if token in " ".join(sequence).lower():
                return {'anomaly': True, 'reason': token}
        return {'anomaly': False}


class LogBERTLike:
    def predict(self, text: str):
        suspicious_keywords = ['encoded', 'obfuscat', 'powershell', 'base64']
        for kw in suspicious_keywords:
            if kw in text.lower():
                return {'anomaly': True, 'keyword': kw}
        return {'anomaly': False}


# -------------------------
# Threat Manager
# -------------------------
class ThreatManager:
    def __init__(self, models: Dict[str, Any]):
        self.models = models
        self.running = False

    async def pull_and_run(self):
        # fetch unprocessed logs
        logs = fetch_unprocessed_logs(limit=200)
        if not logs:
            return
        processed_ids = []
        for r in logs:
            processed_ids.append(r['id'])
            # Basic feature extraction
            features = {
                'bytes_sent': r.get('bytes_sent', 0),
                'bytes_received': r.get('bytes_received', 0),
                'duration': 1
            }
            # Run IsolationForest for simple flow anomalies
            if 'iforest' in self.models:
                out = self.models['iforest'].predict(features)
                if out['anomaly']:
                    write_event('Anomaly: IsolationForest', 'medium', {'score': out['score'], 'log_id': r['id'], 'host': r['host_id']})

            # Run RandomForest network IDS
            if 'netrf' in self.models:
                out = self.models['netrf'].predict(features)
                if out.get('attack'):
                    write_event('Network Attack: RFC', 'high', {'prob': out.get('prob'), 'log_id': r['id']})

            # DeepLog-like sequence detection (if event_text contains sequences)
            if 'deeplog' in self.models:
                seq = r.get('event_text', '').split('|')
                out = self.models['deeplog'].predict(seq)
                if out['anomaly']:
                    write_event('Sequence Anomaly: DeepLog', 'high', {'reason': out.get('reason'), 'log_id': r['id']})

            # LogBERT-like
            if 'logbert' in self.models:
                out = self.models['logbert'].predict(r.get('event_text', ''))
                if out['anomaly']:
                    write_event('Log Semantic Anomaly: LogBERT', 'high', {'keyword': out.get('keyword'), 'log_id': r['id']})

            # Ember-like malware detection (if event_text describes a binary)
            if 'ember' in self.models and 'file_size' in r:
                out = self.models['ember'].predict({'file_size': r.get('file_size'), 'num_imports': r.get('num_imports', 0)})
                if out['malware']:
                    write_event('Malware: EMBER-like', 'critical', {'log_id': r['id']})

        # mark logs processed
        mark_logs_processed(processed_ids)

    async def run_loop(self):
        self.running = True
        while self.running:
            try:
                await self.pull_and_run()
            except Exception as e:
                print('Error in pull_and_run:', e)
            await asyncio.sleep(POLL_INTERVAL_SECONDS)

    def stop(self):
        self.running = False


# -------------------------
# LLM Mitigation (placeholder)
# -------------------------
async def call_llm(prompt: str) -> Dict[str, Any]:
    """Calls Gemini Pro (Generative AI) via REST. Replace the GEMINI_API_KEY with a service account access token
    or use Application Default Credentials with a short-lived OAuth2 token. Set environment variables:
      - GEMINI_API_KEY : Bearer token or API key
      - GEMINI_ENDPOINT : Optional. Defaults to Google Generative API v1beta2 endpoint for Gemini Pro.

    NOTE: Make sure you secure credentials (use secret manager, not hardcoding). This function returns a
    structured JSON if the model responds with JSON, otherwise returns raw text under 'raw'.
    """
    import os
    import aiohttp
    import json

    API_KEY = os.environ.get('GEMINI_API_KEY')
    if not API_KEY:
        # In production, raise or log securely. For prototype, return a helpful dict.
        return {'error': 'GEMINI_API_KEY not set in environment'}

    # Default endpoint for Google Generative API (may change; consult Google docs for most recent path)
    endpoint = os.environ.get('GEMINI_ENDPOINT', 'https://generativelanguage.googleapis.com/v1beta2/models/gemini-pro:generateText')

    # Build request payload. Adjust according to the API version you target.
    payload = {
        'prompt': {
            'text': prompt
        },
        'maxOutputTokens': 512,
        'temperature': 0.0,
        'topP': 0.95
    }

    headers = {
        'Authorization': f'Bearer {API_KEY}',
        'Content-Type': 'application/json'
    }

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(endpoint, headers=headers, json=payload, timeout=30) as resp:
                if resp.status != 200:
                    txt = await resp.text()
                    return {'error': f'LLM request failed with status {resp.status}', 'body': txt}
                data = await resp.json()
    except Exception as e:
        return {'error': 'exception contacting LLM', 'exception': str(e)}

    # API response shapes vary across versions — try common fields
    model_text = None
    # Common v1beta2: data['candidates'][0]['output'] or ['candidates'][0]['content']
    if isinstance(data, dict):
        if 'candidates' in data and isinstance(data['candidates'], list) and len(data['candidates']) > 0:
            cand = data['candidates'][0]
            model_text = cand.get('output') or cand.get('content') or cand.get('text')
        elif 'outputText' in data:
            model_text = data['outputText']
        elif 'response' in data and isinstance(data['response'], dict):
            # some wrappers
            model_text = data['response'].get('outputText') or json.dumps(data['response'])

    if model_text is None:
        # fallback: stringify full response
        model_text = json.dumps(data)

    # Try to parse JSON if the model returned structured JSON
    try:
        parsed = json.loads(model_text)
        return parsed
    except Exception:
        return {'raw': model_text}
, {'action': 'increase_throttle', 'target': 'ssh'}], 'explanation': 'Automated recommendation based on failed auth spike.'}
    if 'exfiltration' in prompt.lower():
        return {'actions': [{'action': 'block_destination', 'target': '8.8.8.8'}, {'action': 'throttle_transfer', 'target': 'host-12', 'percent': 0.0}], 'explanation': 'Large outbound transfer detected.'}
    return {'actions': [{'action': 'notify', 'target': 'sec-team@example.com'}], 'explanation': 'Default action.'}


# -------------------------
# FastAPI app
# -------------------------
app = FastAPI()
manager: ThreatManager = None


class GenerateEventRequest(BaseModel):
    timestamp: str
    host_id: str
    src_ip: str = ''
    dst_ip: str = ''
    event_type: str
    event_text: str
    bytes_sent: int = 0
    bytes_received: int = 0


class MitigationRequest(BaseModel):
    event_id: int
    manual_override: bool = False


@app.on_event("startup")
async def startup_event():
    global manager
    init_db()
    # instantiate models in a loop
    models = {}
    models['iforest'] = SimpleIsolationForestModel(contamination=0.1)
    models['netrf'] = SimpleRandomForestNetModel()
    models['ember'] = EmberLikeMalwareModel()
    models['deeplog'] = DeepLogLike()
    models['logbert'] = LogBERTLike()
    manager = ThreatManager(models=models)
    # start background loop
    asyncio.create_task(manager.run_loop())


@app.post('/generate_event')
async def generate_event(req: GenerateEventRequest):
    write_raw_log(req.dict())
    return {'status': 'ok', 'message': 'event written to DB'}


@app.post('/detect')
async def detect_now(background_tasks: BackgroundTasks):
    # Trigger immediate run
    if manager is None:
        raise HTTPException(status_code=500, detail='Manager not ready')
    background_tasks.add_task(manager.pull_and_run)
    return {'status': 'ok', 'message': 'detection scheduled'}


@app.get('/events')
async def get_events(limit: int = 50):
    return list_events(limit=limit)


@app.post('/mitigate')
async def mitigate(req: MitigationRequest):
    # fetch event details
    evs = list_events(limit=200)
    ev = next((e for e in evs if e['id'] == req.event_id), None)
    if not ev:
        raise HTTPException(status_code=404, detail='event not found')
    # create prompt based on event
    prompt = f"Event: {ev['name']}. Details: {ev['details']}. Provide a structured mitigation plan in JSON."
    llm_response = await call_llm(prompt)
    # store mitigation as event detail (could be separate table)
    write_event('Mitigation: Proposed', 'info', {'event_id': req.event_id, 'plan': llm_response})
    return {'status': 'ok', 'llm_plan': llm_response}


# -------------------------
# Utility: simulate sample threats for testing
# -------------------------
@app.post('/simulate/portscan')
async def simulate_portscan(host_id: str = 'host-1', src_ip: str = '10.0.0.5'):
    # simulate many short flows to many dst ports by writing rows
    for p in [22, 80, 443, 8080, 3306, 8081]:
        write_raw_log({'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'), 'host_id': host_id, 'src_ip': src_ip, 'dst_ip': '192.0.2.5', 'event_type': 'flow', 'event_text': f'port={p}', 'bytes_sent': 50, 'bytes_received': 0})
    return {'status': 'ok', 'message': 'portscan simulated'}


@app.post('/simulate/bruteforce')
async def simulate_bruteforce(host_id: str = 'host-ssh', src_ip: str = '10.0.9.9'):
    # write repeated failed login events
    for i in range(40):
        write_raw_log({'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'), 'host_id': host_id, 'src_ip': src_ip, 'dst_ip': '', 'event_type': 'auth_fail', 'event_text': 'failed login', 'bytes_sent': 0, 'bytes_received': 0})
    return {'status': 'ok', 'message': 'bruteforce simulated'}


@app.post('/simulate/exfil')
async def simulate_exfil(host_id: str = 'host-exfil', dst_ip: str = '198.51.100.9'):
    # single large transfer
    write_raw_log({'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'), 'host_id': host_id, 'src_ip': '10.0.1.5', 'dst_ip': dst_ip, 'event_type': 'flow', 'event_text': 'large outbound', 'bytes_sent': 5000000, 'bytes_received': 10})
    return {'status': 'ok', 'message': 'exfil simulated'}


# -------------------------
# If invoked as script, start uvicorn
# -------------------------
if __name__ == '__main__':
    import uvicorn
    init_db()
    uvicorn.run('detector_prototype_fastapi:app', host='0.0.0.0', port=8000, reload=True)


'''
What’s included:
FastAPI app with endpoints: /generate_event, /detect, /events, /mitigate, and several /simulate/* routes to produce sample threats.
SQLite schema for raw logs + events (starter DB).
ThreatManager that periodically pulls new logs and runs a set of instantiated models (IsolationForest, RandomForest-like network model, Ember-like malware model), plus simulated DeepLog / LogBERT checks.
gemini pro integration 
Background polling loop and examples for simulating port scanning, brute force, and exfiltration.
'''

#needed
#need to agree on an event database..... supabase
#3 pieces of data... monitering for each host (ip address, processes running,3 types of events / threats (monitering events and threat detection events, information that dashboard needs to display by VM)
#
